name: Anahuac_App
description: Calculator for the second term partial exam
# La siguiente línea evita que el paquete se publique accidentalmente en
# pub.dev usando `flutter pub publish`. Esto es preferido para paquetes privados.
publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

# Define la versión y el número de compilación para tu aplicación.
# Un número de versión consta de tres números separados por puntos, como 1.2.43
# seguido opcionalmente por un número de compilación separado por un +.
# Ambos, el número de versión y el de compilación pueden ser sobreescritos en flutter
# build especificando --build-name y --build-number, respectivamente.
# En Android, build-name se utiliza como versionName mientras build-number se utiliza como versionCode.
# Lee más sobre la versión de Android en https://developer.android.com/studio/publish/versioning
# En iOS, build-name se utiliza como CFBundleShortVersionString mientras build-number se utiliza como CFBundleVersion.
# Lee más sobre la versión de iOS en
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# En Windows, build-name se utiliza como la parte mayor, menor y de parche
# de las versiones de productos y archivos mientras que build-number se utiliza como el sufijo de compilación.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logoanahuacmerida.jpg
    - assets/app_icon.jpg
#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700
